version: "3"
services:
    nodeapi:
        image: nodeapi
        build:
          context: .
        ports:
          - "3000:3000"
        depends_on:
            - "mongodb"

    mongodb:
       image: "mongo"
       ports:
         - "27017:27017"
       volumes:
         - /data/mongodb/db:/data/db
